# Generated by Django 5.2.1 on 2025-05-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='delegate_photos/', verbose_name='照片')),
                ('political_status', models.CharField(max_length=50, verbose_name='政治面貌')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('delegation', models.CharField(max_length=100, verbose_name='代表团')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='证件编号')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='发证单位')),
                ('issue_date', models.DateField(verbose_name='签发日期')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='是否已签到')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
            ],
            options={
                'verbose_name': '代表',
                'verbose_name_plural': '代表信息',
            },
        ),
    ]
