# Generated by Django 5.2.1 on 2025-05-15 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate_card_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegate',
            options={'ordering': ['-submitted_at', 'name'], 'verbose_name': '代表信息', 'verbose_name_plural': '代表信息管理'},
        ),
        migrations.AddField(
            model_name='delegate',
            name='approval_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_delegates', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='证件编号'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='签发日期'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发证单位'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='有效期至'),
        ),
    ]
